import Head from "next/head";
import Image from "next/image";
import Herosection from "../components/Herosection";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Herosection/>
      </main>
    </div>
  );
}
