import Head from "next/head";
import CartModal from "../components/CartModal";
import Herosection from "../components/Herosection";
import Meals from "../components/Meals";
import { useCartContext } from "../context/CartContext";

export default function Home() {
  const { sahowCart } = useCartContext();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Herosection />
        <Meals />
        {sahowCart && <CartModal />}
      </main>
    </div>
  );
}
